spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpa_example
    username: postgres
    password: pg_tests

  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false